# Numpy

In [1]:
import numpy as np

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [7]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2.Создать вектор размера 100, заполненный единицами

In [8]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3.Создать вектор размера 100, заполненный числом 3

In [9]:
np.full(100, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [ ]:
numpy.info(numpy.add)

#### 5. Поменять 2 строки в матрице

In [13]:
a = np.diag(np.arange(5))
a[[0, 1]] = a[[1, 0]]
a

array([[0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

#### 6. Создать вектор со значениями от 10 до 100

In [14]:
a = np.arange(10, 101)
a

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### 7. Развернуть вектор (первый становится последним)

In [15]:
a[::-1]

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10])

#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [20]:
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [21]:
nul = np.zeros(17)
a = np.array([1,2,3,4,5])
nul[::4] = a
nul

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 10. Создать 3x3 единичную матрицу

In [23]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Создать массив 3x3x3 со случайными значениями

In [28]:
a = np.random.ranf((3, 3, 3))
a

array([[[0.57830421, 0.33113938, 0.35719079],
        [0.9163245 , 0.53452254, 0.57074441],
        [0.95341474, 0.86137895, 0.64401221]],

       [[0.5548232 , 0.45147431, 0.00316925],
        [0.1168268 , 0.46149798, 0.83066288],
        [0.26592436, 0.58942366, 0.07263126]],

       [[0.50062456, 0.85745747, 0.09028177],
        [0.23986369, 0.51552475, 0.30493858],
        [0.77208485, 0.92804696, 0.66450121]]])

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [70]:
a = np.random.rand(10, 10)
print(a.min())
print(a.max())

0.0015338015515470316
0.9893150045234703


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [89]:
a = np.random.rand(30)
print(a.mean())

0.529293656503629


#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [102]:
a = np.zeros((5,5))
a = np.pad(a,pad_width=1,constant_values=1)
a

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

In [103]:
a = np.array(np.arange(5))
a

array([0, 1, 2, 3, 4])

In [104]:
a.T

array([0, 1, 2, 3, 4])

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [107]:
a = np.diag([1,2,2,4], -1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [116]:
a = np.zeros((8, 8))
a[::2,::2] = 1
a[1::2, 1::2] = 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [118]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [121]:
a = np.array([[1, 0], [0, 1]])
np.tile(a, (4, 4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Перемножить матрицы 5x3 и 3x2

In [124]:
a = np.arange(5*3).reshape(5, 3)
b = np.ones((3, 2))
np.dot(a, b)

array([[ 3.,  3.],
       [12., 12.],
       [21., 21.],
       [30., 30.],
       [39., 39.]])

#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [129]:
a = np.arange(10)
a[(a >= 3) & (a <= 8)] *= -1
a

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9])

#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [130]:
np.tile(np.arange(5), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 24. Есть генератор, сделать с его помощью массив

In [132]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [135]:
a = np.linspace(0, 1, 12)[1:-1]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 26. Отсортировать вектор

In [137]:
a = np.random.rand(10)
a.sort()
a

array([0.04227116, 0.13509101, 0.1707038 , 0.50314649, 0.57123019,
       0.57243121, 0.73357111, 0.77122026, 0.9489875 , 0.97555126])

#### 27. Проверить, одинаковы ли 2 numpy массива

In [150]:
a = np.arange(10).reshape(5, 2)
b = np.arange(10).reshape(5, 2)#[::-1]
print((a == b).all())

False


array([[8, 9],
       [6, 7],
       [4, 5],
       [2, 3],
       [0, 1]])

#### 28. Сделать массив неизменяемым

In [168]:
a = np.zeros(10)
a.flags.writeable = False
try:
    a[0] = 1
except:
    print('Error')        

Error


#### 29. Найти n наибольших значений в массиве

In [188]:
n = 5
a = np.random.randint(0, 50, 20)
print(sorted(a)[-5::])

[34, 38, 40, 41, 45]


#### 30. Заменить максимальный элемент на ноль

In [200]:
a = np.random.randint(0, 10, 10)
a[a.argmax()] = 0
a

array([8, 7, 3, 0, 1, 4, 6, 7, 0, 6])

#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [204]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [209]:
x = np.arange(25).reshape(5, 5)
y = np.arange(25).reshape(5, 5)[::-1] ** 2
c = 1 / (x - y)
c

array([[-0.0025    , -0.00227273, -0.00207469, -0.00190114, -0.00174825],
       [-0.00454545, -0.004     , -0.0035461 , -0.00316456, -0.00284091],
       [-0.01111111, -0.00909091, -0.00757576, -0.00641026, -0.00549451],
       [-0.1       , -0.05      , -0.03125   , -0.02173913, -0.01612903],
       [ 0.05      ,  0.05      ,  0.05555556,  0.07142857,  0.125     ]])

#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [210]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 34. Напечатать все значения в массиве

In [216]:
import sys
np.set_printoptions(threshold=sys.maxsize)
Z = np.zeros((25,25))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [228]:
a = 19
b = np.random.randint(0, 100, 10)
print(b)
b[np.abs(b - a).argmin()]

[50 48 75 68 86 32  4 97  7 17]


17

#### 36. Преобразовать массив из float в int

In [234]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
Z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [236]:
a = np.diag(np.arange(3))
for index, a in np.ndenumerate(a):
    print(index, a)

(0, 0) 0
(0, 1) 0
(0, 2) 0
(1, 0) 0
(1, 1) 1
(1, 2) 0
(2, 0) 0
(2, 1) 0
(2, 2) 2


#### 38. Случайно расположить p элементов в 2D массив

In [242]:
n = 10
p = 10
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), 111)
Z

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 111.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 111.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0., 111.,   0.,   0.,   0.,   0., 111.],
       [  0.,   0.,   0.,   0.,   0., 111.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0., 111.,   0., 111.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0., 111.,   0.,   0.],
       [111.,   0.,   0.,   0., 111.,   0.,   0.,   0.,   0.,   0.]])

#### 39. Отнять среднее из каждой строки в матрице

In [280]:
a = np.random.uniform(0, 100, (7, 2))
a -= a.mean(axis = 1, keepdims=True)
a

array([[-13.02836249,  13.02836249],
       [-14.45144481,  14.45144481],
       [-37.50763022,  37.50763022],
       [ 19.40234592, -19.40234592],
       [-14.15760487,  14.15760487],
       [  4.77654784,  -4.77654784],
       [  0.89870045,  -0.89870045]])

#### 40. Отсортировать матрицу по n-ому столбцу

In [290]:
n = 1
a = np.random.randint(0, 100, (7, 3))
print(a[a[:, 1].argsort()])

[[54 23 88]
 [38 28 71]
 [44 33  7]
 [16 59 29]
 [27 89 21]
 [27 91 34]
 [85 97 70]]


#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [304]:
a = np.random.randint(0, 2, (7, 3))
np.any(np.all(a == 0, axis = 1)), a

(True,
 array([[1, 1, 0],
        [1, 0, 0],
        [0, 0, 1],
        [0, 0, 0],
        [1, 0, 0],
        [0, 1, 1],
        [1, 1, 1]]))

#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [306]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 5. 2. 3. 3. 2. 1. 5. 2. 3.]


#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [307]:
w,h = 16,16
I = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
F = I[...,0] * 256 * 256 + I[...,1] * 256 + I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [308]:
A = np.random.randint(0,10, (3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[58 46 54 54]
 [43 54 65 34]
 [49 52 59 53]]
