# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [136]:
answer(2)

print(np.__version__)
np.show_config()


In [137]:
print(np.__version__)
np.show_config()

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/fedor/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/fedor/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/fedor/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/fedor/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/fedor/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/fedor/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/fedor/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/fedor/anaconda3/include']


#### 3. Create a null vector of size 10 (★☆☆)

In [138]:
a = np.zeros((10))
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [139]:
hint(4)
print(a.itemsize * a.size)

hint: size, itemsize
80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [140]:
answer(5)

%run `python -c "import numpy; numpy.info(numpy.add)"`


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [141]:
a = np.zeros((10))
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [142]:
a = np.arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [143]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [144]:
a = np.arange(0, 9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [145]:
a = np.array([1,2,0,0,4,0] )
print(a.nonzero())

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [146]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [147]:
a = np.random.randn(3, 3, 3)
a

array([[[ 0.14649286, -1.42980442,  0.45951798],
        [ 0.96657895, -1.44422513, -0.23004647],
        [-0.17189107,  1.27738571, -0.52943035]],

       [[ 0.7039137 ,  0.28139961, -0.05292903],
        [ 0.97450056,  0.29189495,  0.24360227],
        [ 0.09701241, -0.02991791, -0.80331089]],

       [[ 0.70550445, -0.74788623,  2.02385317],
        [ 0.67890581, -0.94566433,  0.71194106],
        [-1.56614864,  1.09520756,  1.21005028]]])

In [148]:
answer(12)

Z = np.random.random((3,3,3))
print(Z)


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [149]:
a = np.random.randint(0, 100, (10, 10))
print(a.min())
print(a.max())

0
97


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [150]:
a = np.random.randint(0, 100, 30)
print(a.mean())

39.13333333333333


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [151]:
a = np.ones((5, 5))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [152]:
a = np.ones((5, 5))
np.pad(a, (1, ), 'constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [153]:
answer(17)

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


In [154]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [155]:
a = np.diag(np.arange(4) + 1, k = -1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [156]:
a = np.zeros((8, 8))
a[0::2, 0::2] = 1
a[1::2, 1::2] = 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [157]:
hint(20)
print(np.unravel_index(99, (6, 7, 8)))

hint: np.unravel_index
(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [158]:
a = np.tile([[0, 1], [1, 0]], (4, 4))
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [159]:
answer(22)

Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)


In [160]:
Z = np.random.random((5, 5))
Z = (Z - np.mean(Z)) / np.std(Z)
print(Z)

[[-0.07581313  1.6324565  -1.35211598  0.34353763 -0.34204576]
 [-1.43276058  1.56813375  0.26933631 -1.16365578  0.6919238 ]
 [-1.10760154 -1.47068644 -0.24051863 -0.12346992 -1.2957642 ]
 [ 0.26538377 -1.10631047  1.50293915 -0.64201633  1.37439983]
 [ 1.20883915  0.89952119  0.37688206  0.56587676 -0.34647114]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [161]:
answer(23)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


In [162]:
color = np.dtype([("r", np.ubyte),
                 ("g", np.ubyte),
                 ("b", np.ubyte),
                 ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [163]:
a = np.random.random((5, 3))
b = np.random.random((3, 2))
print(a.dot(b))
print(np.dot(a, b))
print(a @ b)

[[0.659985   0.69452041]
 [1.10612763 0.69516506]
 [0.47352175 0.53885563]
 [0.965886   0.53339356]
 [1.04585181 0.36440926]]
[[0.659985   0.69452041]
 [1.10612763 0.69516506]
 [0.47352175 0.53885563]
 [0.965886   0.53339356]
 [1.04585181 0.36440926]]
[[0.659985   0.69452041]
 [1.10612763 0.69516506]
 [0.47352175 0.53885563]
 [0.965886   0.53339356]
 [1.04585181 0.36440926]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [164]:
a = np.random.randint(0, 10, (10))
a[(a > 3) & (a < 8)] = -a[(a > 3) & (a < 8)]
a

array([-5,  2,  9, -6,  1,  0,  3, -4, -4,  3])

In [165]:
answer(25)

# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)


In [166]:
z = np.arange(11)
z[(3 < z) & (z < 8)] *= -1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [167]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [168]:
Z = np.arange(5)
print(Z)
print(Z**Z)
print(2 << Z  >> 2)
print(Z <- Z)

[0 1 2 3 4]
[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [169]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-169-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-169-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [171]:
hint(29)
a = np.arange(-5, 5)
print(a)
print(np.abs(a))

hint: np.uniform, np.copysign, np.ceil, np.abs, np.where
[-5 -4 -3 -2 -1  0  1  2  3  4]
[5 4 3 2 1 0 1 2 3 4]


In [173]:
answer(29)

# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


In [175]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[ 1.48699336 -2.80966907  7.17340263  3.25892343 -0.74901124  5.1506389
  5.94500837 -2.06218183 -8.07187909  7.46419301]
[ 2. -3.  8.  4. -1.  6.  6. -3. -9.  8.]


In [179]:
a = np.random.uniform(-10,+10,10)
print(a)
print(np.where(a > 0, np.ceil(a), np.floor(a)))

[ 0.06876869  2.21445629 -3.21781709  3.58004789 -3.47803582  6.63942971
 -0.18886531  5.1042258  -0.50161457 -4.88495257]
[ 1.  3. -4.  4. -4.  7. -1.  6. -1. -5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [182]:
a = np.arange(1, 5)
b = np.arange(3, 7)
print(np.intersect1d(a, b))

[3 4]


In [183]:
answer(30)

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [185]:
answer(31)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [190]:
print(np.sqrt(-1) == np.emath.sqrt(-1))
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

False
nan
1j


<ipython-input-190-7a35495fb284>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))
<ipython-input-190-7a35495fb284>:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [192]:
answer(33)

yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)


In [194]:
y = np.datetime64('today') - np.timedelta64(1)
t = np.datetime64('today')
z = np.datetime64('today') + np.timedelta64(1)
print(y)
print(t)
print(z)

2021-08-14
2021-08-15
2021-08-16


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [196]:
answer(34)

Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


In [200]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [204]:
answer(35)
A = np.ones(3)

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


array([1., 1., 1.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [221]:
a = np.random.uniform(0, 10, 10)
print(a)
print(np.floor(a))
print(np.trunc(a))
print(a.astype(int))
print(a // 1)

[1.56488755 4.03672807 3.42574917 2.10885377 9.98331081 1.0443798
 9.09419917 3.71850345 0.48034618 2.3798198 ]
[1. 4. 3. 2. 9. 1. 9. 3. 0. 2.]
[1. 4. 3. 2. 9. 1. 9. 3. 0. 2.]
[1 4 3 2 9 1 9 3 0 2]
[1. 4. 3. 2. 9. 1. 9. 3. 0. 2.]


In [214]:
hint(36)

hint: %, np.floor, astype, np.trunc


In [222]:
answer(36)

Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [234]:
a = np.zeros((5, 5))
a[::] = np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [236]:
answer(37)

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [238]:
answer(38)

def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [243]:
print(np.linspace(0,1,10,endpoint=False)[1::])

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [246]:
a = np.random.randn(10)
a.sort()
a

array([-1.58976278, -1.0120911 , -0.97771926, -0.7553681 , -0.65834847,
       -0.40627775,  0.11527501,  0.21211483,  0.58841134,  0.88944406])

In [247]:
answer(40)

Z = np.random.random(10)
Z.sort()
print(Z)


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [249]:
a = np.arange(100)
%timeit np.sum(a)
%timeit np.add.reduce(a)

2.99 µs ± 28.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
931 ns ± 11.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [250]:
answer(42)

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)


#### 43. Make an array immutable (read-only) (★★☆)

In [252]:
answer(43)

Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


In [262]:
a = np.zeros(10)
a.flags.writeable = False
try:
    a[1] = 0
except:
    print('only writeable')

only writeable


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [284]:
hint(44)
z = np.random.random((10, 2))
x = z[:, 0]
y = z[:, 1]
l = np.sqrt(x**2 + y**2)
a = np.arctan2(y, x)
print(l)
print(a)

hint: np.sqrt, np.arctan2
[0.55052463 1.30635153 0.58957236 0.2924093  0.83245868 0.53480157
 0.69349458 1.11249132 0.906567   0.91826411]
[0.10686103 0.75953087 0.21386027 0.41321246 0.76129947 0.38174445
 1.45097443 0.64048168 0.99951179 0.73972796]


In [285]:
answer(44)

Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [297]:
a = np.random.randint(0, 10, 10)
print(a)
a[a == a.max()] = 0
a

[5 3 6 5 1 5 7 7 9 6]


array([5, 3, 6, 5, 1, 5, 7, 7, 0, 6])

In [298]:
answer(45)

Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [301]:
x = np.linspace(0, 1, 10)
y = np.linspace(0, 1, 10)
XY = np.meshgrid(x, y)
XY

[array([[0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
         0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
        [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
         0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
        [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
         0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
        [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
         0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
        [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
         0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
        [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
         0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
        [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
         0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
        [0.        , 0.1111

In [302]:
answer(46)

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [306]:
x = np.random.random((5, 5))
y = np.random.random((5, 5))
c = 1 / (x - y)
c

array([[ -2.01815341,  -3.15077484,  -1.5309506 ,  -2.03353932,
         65.62287482],
       [ -1.50838952,   6.04971881,  -2.14635397,  -1.6764179 ,
          4.68851677],
       [-13.83357762,  -1.27510418,  -2.6452137 ,   6.47152886,
         18.70872084],
       [-37.2215512 ,   1.18266227,   3.31649512,  -2.56940479,
          1.50788249],
       [  3.66856892,  -4.14859845,   6.1459624 ,  -4.70131314,
          3.0693859 ]])

In [307]:
answer(47)

# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [310]:
answer(48)

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)


In [311]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [315]:
answer(49)

np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)


In [316]:
np.set_printoptions(threshold=float("inf"))
a = np.zeros((40, 40))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [331]:
a = np.random.randint(0, 100, 10)
b = np.abs(a - 50)
print(a)
a[b.argmin()]

[28 63 42 94 38 48 50 93 17 84]


50

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [5]:
answer(51)
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)
[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-5-51f26607c17d>:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [7]:
answer(52)

Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)


In [18]:
Z = np.random.random((10, 2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
D

array([[0.        , 0.63427647, 0.56794187, 0.38385495, 0.46291322,
        0.27269751, 0.84399112, 0.55814689, 1.04359318, 0.47110216],
       [0.63427647, 0.        , 0.36383584, 0.73116446, 0.63719153,
        0.65072258, 0.52443547, 0.62199619, 0.61760176, 0.2183626 ],
       [0.56794187, 0.36383584, 0.        , 0.84069847, 0.32017849,
        0.4284727 , 0.86895737, 0.84455731, 0.9807556 , 0.19957661],
       [0.38385495, 0.73116446, 0.84069847, 0.        , 0.83023045,
        0.65381441, 0.6649032 , 0.26993543, 0.88274172, 0.67350625],
       [0.46291322, 0.63719153, 0.32017849, 0.83023045, 0.        ,
        0.20457081, 1.0767954 , 0.93172654, 1.22655298, 0.42214245],
       [0.27269751, 0.65072258, 0.4284727 , 0.65381441, 0.20457081,
        0.        , 1.00666128, 0.79439086, 1.18174689, 0.43744768],
       [0.84399112, 0.52443547, 0.86895737, 0.6649032 , 1.0767954 ,
        1.00666128, 0.        , 0.40512709, 0.21783975, 0.68004305],
       [0.55814689, 0.62199619, 0.8445573

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [23]:
a = np.linspace(0, 1, 10, dtype='float32')
print(a)
b = a.view(dtype='int32')[:]
print(b)

[0.         0.11111111 0.22222222 0.33333334 0.44444445 0.5555556
 0.6666667  0.7777778  0.8888889  1.        ]
[         0 1038323257 1046711865 1051372203 1055100473 1057896676
 1059760811 1061624946 1063489081 1065353216]


In [24]:
answer(53)

# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)


In [28]:
Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[84.83246  18.271591 33.75439  78.44014  23.795223 61.156372 26.980984
 28.238398 99.56794  81.71047 ]
[84 18 33 78 23 61 26 28 99 81]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [29]:
hint(54)

hint: np.genfromtxt


In [4]:
import re
import numpy as np
#file = open('file.txt', 'r')
mas = np.array([])
for line in file:
    line = line.rstrip()
    mas = np.hstack((mas, list(map(int, filter(None, re.split(r'\s|,', line))))))
print(mas)

NameError: name 'file' is not defined

In [5]:
answer(54)

from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)


In [14]:
from io import StringIO
# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
a = str(s).split(',')
print(a)
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

['<_io.StringIO object at 0x7f513a25cee0>']
[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-14-fd994ccfb97b>:11: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [20]:
a = np.arange(9).reshape(3, 3)
for i, val in np.ndenumerate(a):
    print(i, val)
print(a.shape)
for index in np.ndindex(a.shape):
    print(index, a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(3, 3)
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [21]:
answer(56)

X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [22]:
hint(57)

hint: np.put, np.random.choice


In [40]:
n = 5
p = 10
a = np.zeros((n, n))
np.put(a, np.random.choice(n*n,p, replace=False), np.arange(p) + 1)
a

array([[ 0.,  0.,  3.,  9.,  0.],
       [ 1.,  0.,  7.,  0.,  0.],
       [ 0.,  5.,  0.,  0.,  0.],
       [ 0.,  4.,  0.,  0.,  0.],
       [ 0.,  6.,  8.,  2., 10.]])

In [38]:
answer(57)

# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [55]:
a = np.ceil(np.random.sample(25).reshape(5, 5) * 100)
m = np.mean(a, axis=1, keepdims=True)
print(a - m)
print(np.sum(a -m, axis = 1, keepdims = True))

[[ 39.2 -36.8  20.2 -41.8  19.2]
 [ 40.   -8.  -48.   22.   -6. ]
 [  9.4  39.4  24.4 -36.6 -36.6]
 [ -8.6  51.4 -21.6 -16.6  -4.6]
 [-45.6  30.4  18.4 -36.6  33.4]]
[[ 1.42108547e-14]
 [ 0.00000000e+00]
 [-1.42108547e-14]
 [-7.10542736e-15]
 [-7.10542736e-15]]


In [49]:
hint(58)

hint: mean(axis=,keepdims=)


#### 59. How to sort an array by the nth column? (★★☆)

In [82]:
n = 2
a = np.zeros((5, 5))
mas = np.random.randint(0, 100, 5)
a[:, n] = mas
print(a[a[:, n].argsort()])

[[ 0.  0. 11.  0.  0.]
 [ 0.  0. 27.  0.  0.]
 [ 0.  0. 28.  0.  0.]
 [ 0.  0. 29.  0.  0.]
 [ 0.  0. 36.  0.  0.]]


In [77]:
answer(59)

# Author: Steve Tjoa

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [111]:
a = np.random.randint(0,2,(3, 10))
print(a)
print((~np.any(a, axis=0)).any())

[[1 1 0 1 0 1 1 0 0 1]
 [1 0 1 0 1 1 1 0 1 1]
 [1 0 0 1 1 1 0 1 1 1]]
False


In [87]:
hint(60)

hint: any, ~


In [86]:
answer(60)

# Author: Warren Weckesser

Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())


#### 61. Find the nearest value from a given value in an array (★★☆)

In [139]:
a = np.random.randint(0, 100, 10)
p = 77
b = a[np.abs(a - p).argmin()]
print(a)
print(b)

[48 67 14 98 90 60 99 41 76 22]
76


In [138]:
answer(61)

Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [140]:
answer(62)

A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])


In [141]:
hint(62)

hint: np.nditer


#### 63. Create an array class that has a name attribute (★★☆)

In [143]:
answer(63)

class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [144]:
hint(64)

hint: np.bincount | np.add.at


In [147]:
a = np.zeros(10)
np.add.at(a, [2, 5, 2], 1)
a

array([0., 0., 2., 0., 0., 1., 0., 0., 0., 0.])

In [148]:
answer(64)

# Author: Brett Olsen

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [150]:
answer(65)

# Author: Alan G Isaac

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)


In [151]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [153]:
answer(66)

# Author: Fisher Wang

w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

# Faster version
# Author: Mark Setchell
# https://stackoverflow.com/a/59671950/2836621

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [155]:
answer(67)

A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [159]:
answer(68)

# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())


#### 69. How to get the diagonal of a dot product? (★★★)

In [169]:
hint(69)
a = np.random.randint(0, 10, (3, 2))
b = np.random.randint(0, 10, (2, 3))
c = np.dot(a, b)
print(c)
print(np.diag(c))

hint: np.diag
[[72 37 13]
 [45 24  9]
 [45 27 12]]
[72 24 12]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [176]:
b = np.array([1, 2, 3, 4, 5])
a = np.zeros(17)
a[::4] = b
print(a)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [177]:
answer(70)

# Author: Warren Weckesser

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [179]:
answer(71)

A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])


#### 72. How to swap two rows of an array? (★★★)

In [200]:
a = np.ones((5, 5))
a[::2] = np.arange(5)
a[[0, 1]] = a[[1, 0]]
a

array([[1., 1., 1., 1., 1.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [1., 1., 1., 1., 1.],
       [0., 1., 2., 3., 4.]])

In [186]:
answer(72)

# Author: Eelco Hoogendoorn

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [204]:
answer(73)

# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [209]:
a = np.random.randint(0, 5, 5)
b = np.repeat(np.arange(5), a)
print(a)
print(b)

[1 2 1 1 4]
[0 1 1 2 3 4 4 4 4]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [214]:
a = np.arange(5)
b = np.cumsum(a)
c = np.arange(5) + 1
print(b)
print(b / c)

[ 0  1  3  6 10]
[0.  0.5 1.  1.5 2. ]


In [218]:
a = np.arange(5)
n = 3
print([sum(a[i:i + n]) / n for i in range(len(a) - n + 1)])

[1.0, 2.0, 3.0]


In [219]:
answer(75)

# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [8]:
hint(76)

hint: from numpy.lib import stride_tricks


In [5]:
answer(76)

# Author: Joe Kington / Erik Rigtorp
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)


In [7]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [9]:
hint(77)

hint: np.logical_not, np.negative


In [11]:
answer(77)

# Author: Nathaniel J. Smith

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)


In [17]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.9864576 , -0.36693728, -0.37119144, -0.88369466,  0.4379148 ,
        0.80973454, -0.89131775,  0.79566661, -0.22235394, -0.55805393,
       -0.80471562, -0.17687438,  0.46913879, -0.72703202, -0.87796967,
        0.04908328, -0.87810274, -0.06401964, -0.06394039, -0.99473595,
        0.95089904, -0.64270669, -0.72998383, -0.25812064, -0.54762869,
       -0.82676515,  0.54313926,  0.60895591, -0.07355687, -0.11439196,
       -0.00530436,  0.82292718, -0.1389211 ,  0.76448587, -0.92016633,
        0.45097893,  0.10221562, -0.34508019,  0.57229886, -0.24282081,
       -0.92376177, -0.87477302,  0.82906996,  0.45572719, -0.211508  ,
       -0.44117056,  0.53818719, -0.27182853,  0.60700719,  0.57600821,
        0.18815781, -0.68826205, -0.13429466,  0.90383014, -0.38269095,
        0.36583205, -0.47259588,  0.24951651,  0.82813395, -0.3889184 ,
        0.7977712 ,  0.94989895,  0.99294233,  0.41745247, -0.2761257 ,
        0.85422082,  0.13057162, -0.68444305,  0.07127387, -0.94

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [19]:
answer(78)

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [20]:
answer(79)

# Author: Italmassov Kuanysh

# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [23]:
answer(80)

# Author: Nicolas Rougier

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [25]:
Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
n = 4
a = np.array([Z[i:i + n] for i in range(len(Z) - n)])
print(a)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]]


In [26]:
answer(81)

# Author: Stefan van der Walt

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)


#### 82. Compute a matrix rank (★★★)

In [28]:
hint(82)

hint: np.linalg.svd, np.linalg.matrix_rank


In [31]:
a = np.eye(5)
print(np.linalg.matrix_rank(a))

5


#### 83. How to find the most frequent value in an array?

In [49]:
from collections import Counter
a = np.random.randint(100, 105, 10)
print(a)
Counter(a).most_common(1)

[104 104 100 104 104 100 104 100 102 100]


[(104, 5)]

In [38]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z))
print(np.bincount(Z).argmax())

[4 2 4 9 5 6 8 5 3 4]
3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [51]:
answer(84)

# Author: Chris Barker

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [53]:
answer(85)

# Author: Eric O. Lebigot
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [55]:
answer(86)

# Author: Stefan van der Walt

p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [57]:
answer(87)

# Author: Robert Kern

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

# alternative solution:
# Author: Sebastian Wallkötter (@FirefoxMetzger)

Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [58]:
answer(88)

# Author: Nicolas Rougier

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)


In [6]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(10,10))
for i in range(100): print(Z); Z = iterate(Z);

[[0 1 1 0 0 1 0 0 1 1]
 [1 0 1 1 1 0 1 0 0 0]
 [0 1 0 0 1 1 1 1 0 1]
 [0 1 0 0 0 0 0 0 1 1]
 [1 1 0 1 1 0 1 0 0 0]
 [1 0 1 0 0 0 0 0 1 1]
 [1 0 1 0 0 1 1 1 0 1]
 [1 1 0 1 0 0 0 0 0 1]
 [0 1 1 1 1 0 1 0 0 0]
 [0 0 0 0 0 1 0 1 1 1]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 1 0 1 1 0 0]
 [0 1 0 1 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 1 0 0]
 [0 0 1 0 1 0 0 0 1 0]
 [0 0 1 1 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 1 1 0]
 [0 1 0 1 1 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 1 0 0]
 [0 0 0 1 1 0 1 0 1 0]
 [0 0 0 1 1 0 0 1 1 0]
 [0 0 1 0 1 0 1 0 1 0]
 [0 0 1 1 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 1 0 0]
 [0 0 1 0 1 1 1 0 1 0]
 [0 0 1 0 0 0 1 0 1 0]
 [0 0 1 0 1 0 1 0 1 0]
 [0 0 1 1 0 1 0 0 0 0]
 [0 0 0 1 1 0 0 0 1 0]
 [0 0 0 0 0 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 1 1 0 0]
 [0 0 1

#### 89. How to get the n largest values of an array (★★★)

In [15]:
n = 5
mas = np.sort(np.random.randint(1, 100, 20))[::-1]
print(mas[:5])

[93 88 87 84 81]


In [16]:
answer(89)

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [17]:
answer(90)

# Author: Stefan Van der Walt

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))


#### 91. How to create a record array from a regular array? (★★★)

In [20]:
hint(91)
answer(91)

hint: np.core.records.fromarrays
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)


In [21]:
hint: np.core.records.fromarrays
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [26]:
z = np.random.randint(0, 100, 10)
print(z**3)
print(np.power(z, 3))
hint(92)

[110592  59319 456533     27 216000 343000   1000 195112  97336  10648]
[110592  59319 456533     27 216000 343000   1000 195112  97336  10648]
hint: np.power, *, np.einsum


In [27]:
answer(92)

# Author: Ryan G.

x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)


In [29]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)
%timeit x**3

871 ms ± 16.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
166 ms ± 693 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
136 ms ± 446 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
861 ms ± 2.55 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [58]:
a = np.random.randint(0, 10, (8, 3))
print(a)
b = np.random.randint(0, 10, (2, 2))
print(b)
fin = np.arange(3)
print(list(filter(lambda x: np.intersect1d(x, b[0]).size * np.intersect1d(x, b[1]).size > 0, a)))

[[6 9 8]
 [5 6 1]
 [6 4 4]
 [9 4 9]
 [5 2 3]
 [0 8 3]
 [2 8 7]
 [1 9 4]]
[[1 8]
 [9 5]]
[array([6, 9, 8]), array([5, 6, 1]), array([1, 9, 4])]


In [61]:
answer(93)

# Author: Gabe Schwartz

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)
[0 3 4 5]


In [63]:
# Author: Gabe Schwartz

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
print(A)
print(B)
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[[2 4 3]
 [4 2 0]
 [0 2 2]
 [0 0 3]
 [3 1 3]
 [2 3 4]
 [0 0 0]
 [0 3 3]]
[[1 0]
 [4 1]]
[1 4]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [124]:
a = np.random.randint(0, 3, (10, 3))
print(a)
bol = list(map(lambda x: x == x[0], a))
mask1 = list(map(lambda x: not x, (map(all, bol))))
print(mask1)
print(a[mask1])

[[0 0 2]
 [2 1 0]
 [1 0 1]
 [1 1 0]
 [1 0 1]
 [2 0 0]
 [0 0 0]
 [2 0 2]
 [0 2 1]
 [2 1 2]]
[True, True, True, True, True, True, False, True, True, True]
[[0 0 2]
 [2 1 0]
 [1 0 1]
 [1 1 0]
 [1 0 1]
 [2 0 0]
 [2 0 2]
 [0 2 1]
 [2 1 2]]


In [126]:
answer(94)

# Author: Robert Kern

Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)


In [10]:
# Author: Robert Kern

Z = np.random.randint(0,3,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 0 0]
 [0 0 0]
 [0 0 2]
 [0 2 2]
 [1 1 1]
 [1 0 0]
 [1 1 0]
 [0 0 1]
 [2 1 0]
 [0 2 1]]
[[1 0 0]
 [0 0 2]
 [0 2 2]
 [1 0 0]
 [1 1 0]
 [0 0 1]
 [2 1 0]
 [0 2 1]]
[[1 0 0]
 [0 0 2]
 [0 2 2]
 [1 0 0]
 [1 1 0]
 [0 0 1]
 [2 1 0]
 [0 2 1]]


In [14]:
print(np.all(Z[:, 1:] == Z[:, :-1], axis = 1))

[False  True False False  True False False False False False]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [26]:
a = np.arange(5, dtype=np.uint8)
print(np.unpackbits(a[:, np.newaxis], axis = 1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0]]


In [25]:
answer(95)

# Author: Warren Weckesser

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [49]:
a = np.random.randint(0, 3, (10, 2))
print(a)
print(np.where(a == [1, 2])) #this is not correct to find rows

[[1 2]
 [0 0]
 [1 0]
 [0 1]
 [2 1]
 [0 2]
 [2 2]
 [1 2]
 [1 1]
 [0 0]]
(array([0, 0, 2, 5, 6, 7, 7, 8]), array([0, 1, 0, 1, 1, 0, 1, 0]))


In [50]:
(a == [1, 2]).all(axis=1).nonzero() #this method should be prefer

(array([0, 7]),)

In [58]:
np.where((a == (1, 2)).all(axis=1)) #np.where using to get the indices (the same as nonzero)

(array([0, 7]),)

In [25]:
answer(96)

# Author: Jaime Fernández del Río

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)


In [26]:
a = np.random.randint(0, 3, (8, 2))
print(a)
print(np.unique(a, axis = 0))

[[2 2]
 [0 2]
 [2 0]
 [0 0]
 [1 2]
 [0 1]
 [1 1]
 [0 1]]
[[0 0]
 [0 1]
 [0 2]
 [1 1]
 [1 2]
 [2 0]
 [2 2]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [59]:
answer(97)

# Author: Alex Riley
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)


In [60]:
# Author: Alex Riley
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.00757704, 0.02144097, 0.00800107, 0.01970793, 0.00437607,
        0.01718794, 0.00590263, 0.00832014, 0.00206401, 0.00501542],
       [0.26061778, 0.73747824, 0.27520273, 0.67786896, 0.15051817,
        0.59119197, 0.20302537, 0.28617726, 0.07099305, 0.17250924],
       [0.281403  , 0.79629483, 0.29715116, 0.7319315 , 0.16252254,
        0.63834169, 0.21921738, 0.30900095, 0.076655  , 0.18626748],
       [0.11746591, 0.33239694, 0.12403966, 0.30552979, 0.0678417 ,
        0.26646264, 0.0915078 , 0.12898611, 0.03199806, 0.07775354],
       [0.24306328, 0.68780373, 0.25666583, 0.63220958, 0.14037968,
        0.5513709 , 0.18935014, 0.26690115, 0.06621115, 0.16088949],
       [0.16935146, 0.4792191 , 0.17882888, 0.44048453, 0.09780788,
        0.38416115, 0.13192746, 0.18596022, 0.04613183, 0.11209785],
       [0.10726936, 0.30354346, 0.11327248, 0.27900849, 0.06195275,
        0.24333254, 0.08356453, 0.11778956, 0.02922049, 0.0710042 ],
       [0.00392449, 0.01110526, 0.0041441

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [62]:
answer(98)

# Author: Bas Swinckels

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [66]:
a = np.random.randint(0, 3, (10, 2)) #outputing rows that sums into 2
print(a)
a[np.sum(a, axis = 1) == 2]

[[0 0]
 [1 1]
 [1 0]
 [0 2]
 [0 2]
 [0 0]
 [1 1]
 [1 1]
 [2 0]
 [1 2]]


array([[1, 1],
       [0, 2],
       [0, 2],
       [1, 1],
       [1, 1],
       [2, 0]])

In [68]:
answer(99)

# Author: Evgeni Burovski

X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [69]:
answer(100)

# Author: Jessica B. Hamrick

X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)
